# Generated by Django 3.2.7 on 2021-10-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_accessed',
            field=models.DateTimeField(null=True, verbose_name='Последний просмотр'),
        ),
    ]
